# Generated by Django 3.2.7 on 2021-12-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='best_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Best Time'),
        ),
    ]
